openapi: 3.0.0
info:
  title: FolkSoul API
  description: API documentation of FolkSoul API
  version: 0.1.9

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

servers:
  - url: https://folksoul-api.sabavar.redberryinternship.ge
    description: production server
  - url: http://localhost:5001/
    description: local server

# Authentication
paths:
  /auth:
    post:
      tags:
        - Authentication
      description: Generate JWT token to access forbidden content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
            example:
              username: 'username'
              password: 'password'
      responses:
        '201':
          description: JWT token generated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                example:
                  token: 'JWT token'
        '404':
          description: Credentials are incorrect.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'მომხმარებელი ვერ მოიძებნა'

  # Member
  /all-members:
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          description: Fetch certain 3 users according to page parameter
      tags:
        - Member
      description: Fetch list of all band members
      responses:
        '200':
          description: Members list successfully fetched.
          content:
            application/json:
              schema:
                type: object
                properties:
                  members:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        name:
                          type: string
                        instrument:
                          type: string
                        orbitLength:
                          type: integer
                        color:
                          type: string
                        biography:
                          type: string
                        image:
                          type: string
                example:
                  members:
                    - _id: 62d69cff3bcf9b29fe0cc1fa
                      name: ნიკა
                      instrument: სალამური
                      orbitLength: 269
                      color: '#000000'
                      biography: 'დაიბადა ...'
                      image: 'images/members/image.png'
        '500':
          description: Internal Server Error.

  /get-one-member:
    get:
      security:
        - bearerAuth: []
      tags:
        - Member
      description: Fetch details of certain band member
      parameters:
        - in: query
          required: true
          name: id
          schema:
            type: string
          description: Fetch data of certain band member
      responses:
        '200':
          description: Member details successfully fetched.
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  name:
                    type: string
                  instrument:
                    type: string
                  orbitLength:
                    type: number
                  color:
                    type: string
                  biography:
                    type: string
                  image:
                    type: string
                example:
                  _id: '62d5bc4a3bcf9b29fe0cc104'
                  name: 'ვეფხია'
                  instrument: 'დუდუკი'
                  orbitLength: 100
                  color: '#000000'
                  biography: 'დაიბადა ...'
                  image: 'images/members/image.png'
        '404':
          description: Member not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'ბენდის წევრი ვერ მოიძებნა!'
        '422':
          description: Unprocessed Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'წევრის id არ არის ვალიდური'

  /add-member:
    post:
      security:
        - bearerAuth: []
      tags:
        - Member
      description: Add one Member to band
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                instrument:
                  type: string
                orbitLength:
                  type: number
                color:
                  type: string
                biography:
                  type: string
            example:
              name: 'ვეფხია'
              instrument: 'დუდუკი'
              orbitLength: 100
              color: '#000000'
              biography: 'დაიბადა ...'
      responses:
        '201':
          description: Member saved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'ბენდს წევრი წარმატებით დაემატა!'
        '409':
          description: Member already exists.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: "'წევრის სახელი' უკვე არის ბენდის წევრი!"
        '422':
          description: Unprocessed Entity
        '500':
          description: Internal Server Error.

  /upload-member-image:
    patch:
      security:
        - bearerAuth: []
      tags:
        - Member
      description: Upload avatar photo of certain band member
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                id:
                  type: string
                image:
                  type: string
                  format: binary
            example:
              id: '62cd66b2bc4b70708a73125f'
      responses:
        '201':
          description: Member avatar photo uploaded successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'ბენდის წევრის ავატარი წარმატებით აიტვირთა!'
        '404':
          description: Member not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'ბენდის წევრი ვერ მოიძებნა!'
        '422':
          description: Unprocessed Entity

  /change-member:
    put:
      security:
        - bearerAuth: []
      tags:
        - Member
      description: Change details of certain band member
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                instrument:
                  type: string
                orbitLength:
                  type: number
                color:
                  type: string
                biography:
                  type: string
            example:
              id: '62cd66b2bc4b70708a73125f'
              name: 'ევგენი'
              instrument: 'სალამური'
              orbitLength: 100
              color: '#000000'
              biography: 'დაიბადა ...'
      responses:
        '200':
          description: Member details changed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'წევრის ინფორმაცია შეიცვალა!'
        '404':
          description: Not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'წევრი ვერ მოიძებნა'
        '409':
          description: Member with this name already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: "'წევრის სახელი' უკვე არის ბენდის წევრი!"
        '422':
          description: Unprocessed Entity

  /delete-member:
    delete:
      parameters:
        - in: query
          name: id
          schema:
            type: string
      security:
        - bearerAuth: []
      tags:
        - Member
      description: Delete one member from the band
      responses:
        '200':
          description: Member deleted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'ბენდის წევრი წაიშალა!'
        '404':
          description: Member not found to delete.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'წევრი ვერ მოიძებნა'
        '422':
          description: Unprocessed Entity
        '500':
          description: Server Error

  # Social Link
  /all-links:
    get:
      tags:
        - Social Link
      description: Fetch list of all social links
      responses:
        '200':
          description: Social Links successfully fetched.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    linkName:
                      type: string
                    url:
                      type: string
                    image:
                      type: integer
                example:
                  - _id: 62d5832f3bcf9b29fe0cbf61
                    linkName: github
                    url: github.com
                    image: images/social-links/link.png
        '500':
          description: Internal Server Error

  /add-social-link:
    post:
      security:
        - bearerAuth: []
      tags:
        - Social Link
      description: Add social link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                linkName:
                  type: string
                url:
                  type: string
            example:
              linkName: 'google'
              url: 'google.com'
      responses:
        '201':
          description: Social link saved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'სოციალური ბმული წარმატებით შეინახა!'
        '409':
          description: Social link already exists.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: "სოციალური ბმული 'სახელი' უკვე არსებობს"
        '422':
          description: Unprocessed Entity
        '500':
          description: Internal Server Error.

  /upload-link-image:
    patch:
      security:
        - bearerAuth: []
      tags:
        - Social Link
      description: Upload photo of certain social link
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                id:
                  type: string
                image:
                  type: string
                  format: binary
            example:
              id: '62cd66b2bc4b70708a73125f'
      responses:
        '201':
          description: Social link photo uploaded successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'სოციალური ბმულის სურათი წარმატებით აიტვირთა'
        '404':
          description: Social link not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'სოციალური ბმული ვერ მოიძებნა'
        '422':
          description: Unprocessed Entity

  /change-link:
    put:
      security:
        - bearerAuth: []
      tags:
        - Social Link
      description: Change details of certain social Link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                linkName:
                  type: string
                url:
                  type: string
            example:
              id: '62cd66b2bc4b70708a73125f'
              linkName: 'amazon'
              url: 'amazon.com'
      responses:
        '200':
          description: Social link details changed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'სოციალური ბმულის ინფორმაცია შეიცვალა'
        '409':
          description: Social link already exists.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: "'ლინკის სახელი' უკვე დამატებულია"
        '422':
          description: Unprocessed Entity

  /delete-link:
    delete:
      parameters:
        - in: query
          name: id
          schema:
            type: string
      security:
        - bearerAuth: []
      tags:
        - Social Link
      description: Delete certain social link
      responses:
        '200':
          description: Social link deleted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'სოციალური ბმული წაიშალა!'
        '404':
          description: Unprocessed Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'სოციალური ბმული ვერ მოიძებნა'
        '422':
          description: Unprocessed Entity
        '500':
          description: Internal Server Error.

  # Band
  /band-about:
    get:
      tags:
        - Band
      description: Fetch details about band
      responses:
        '200':
          description: Band details successfully fetched.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    about:
                      type: string
                    image:
                      type: string
                example:
                  - _id: 62d5832f3bcf9b29fe0cbf61
                    about: ბენდი დაარსდა
                    url: band.com
                    image: images/band/link.png
        '500':
          description: Internal Server Error.

  /upload-band-image:
    patch:
      security:
        - bearerAuth: []
      tags:
        - Band
      description: Upload photo of band
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                id:
                  type: string
                image:
                  type: string
                  format: binary
            example:
              id: '62cd66b2bc4b70708a73125f'
      responses:
        '201':
          description: Band photo uploaded successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'ბენდის სურათი წარმატებით აიტვირთა'
        '404':
          description: Band not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'ბენდი ვერ მოიძებნა'
        '422':
          description: Unprocessed Entity
        '500':
          description: Internal Server Error.

  /change-band-about:
    put:
      security:
        - bearerAuth: []
      tags:
        - Band
      description: Change details of band
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                about:
                  type: string
            example:
              id: '62cd66b2bc4b70708a73125f'
              about: 'ბენდი დაარსდა ...'
      responses:
        '200':
          description: Band details changed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'ბენდის ინფორმაცია წარმატებით შეიცვალა!'
        '404':
          description: Band not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'ბენდი ჯერ არ არსებობს'
        '422':
          description: Unprocessed Entity
        '500':
          description: Internal Server Error.
